name: Copr Build for CI

inputs:
  copr-user:
    description: The Copr user to build packages under
    required: true

outputs:
  package-urls:
    description: The URLs of built RPM packages
    value: ${{steps.copr-build.outputs.package-urls}}

runs:
  using: "composite"
  steps:
    - name: Rebase the pull request on target branch
      shell: bash
      run: |
        pushd gits/${{github.event.pull_request.head.repo.name}}
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "Rebasing \"`git log --oneline -1`\" on ${{github.event.pull_request.base.ref}}: \"`git log --oneline -1 origin/${{github.event.pull_request.base.ref}}`\""
        git rebase origin/${{github.event.pull_request.base.ref}}
        popd

    - name: Build packages in Copr
      id: copr-build
      shell: bash
      run: |
        PROJECT_NAME="CI-${{github.event.pull_request.head.repo.name}}-pr${{github.event.pull_request.number}}"
        # if there's a git already checked out in the `gits` directory, rpm-gitoverlay will use it
        rpm-gitoverlay -o rpmlist --gitdir=gits build-overlay -s overlays/dnf-ci rpm copr --owner "${{inputs.copr-user}}" --project "$PROJECT_NAME" --chroot fedora-33-x86_64 --delete-project-after-days=7

        # delete the Copr secret just to be on the safe(er) side when running potentially untrusted PR code (albeit in a container, which should be secure)
        rm -rf "$HOME/.config/copr"

        # convert newlines to spaces (output variable assignment below doesn't support newlines)
        PACKAGE_URLS="$(tr '\n' ' ' < rpmlist)"
        echo "::set-output name=package-urls::$PACKAGE_URLS"
