# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
    manual_trigger: true
    skip_build: true
