name: Setup DNF CI

inputs:
  copr-user:
    required: true
  copr-api-token:
    required: true
  fail-without-copr:
    description: Whether to fail if Copr isn't configured. If false, the action will pass and the copr-user output will be empty.
    required: false
    default: true

outputs:
  copr-user:
    description: A cleaned-up Copr user (see the hack below about the workaround for Github secret scrubbing)
    value: ${{steps.copr-setup.outputs.copr-user}}

runs:
  using: "composite"
  steps:
    - id: copr-setup
      shell: bash
      run: |
        # hack: Github replaces secrets with *** in the whole output (even in
        # e.g. Copr URLs printed by rpm-gitoverlay). If there's a comment (#)
        # at the end of the secret (e.g.  "rpmsofwaremanagement #"), this
        # will clean it up and since it is no longer the whole secret being
        # printed, Github won't hide it anymore.
        COPR_USER=${{inputs.copr-user}}
        if [ "${{inputs.fail-without-copr}}" = true -a -z "$COPR_USER" ]; then echo "COPR_USER secret is required to run the CI."; exit 1; fi
        echo "::set-output name=copr-user::$COPR_USER"

        if [ "${{inputs.fail-without-copr}}" = true -a -z "${{inputs.copr-api-token}}" ]; then echo "COPR_API_TOKEN secret is required to run the CI."; exit 1; fi
        mkdir -p "$HOME/.config"
        echo "${{inputs.copr-api-token}}" > "$HOME/.config/copr"
