name: Run DNF Integration Tests

inputs:
  suite:
    description: The suite to run (default is "dnf", which is in the "features" directory)
  package-urls:
    description: The URLs of RPM packages to test
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Integration Tests
      shell: bash
      run: |
        # needed for podman user containers to work
        export STORAGE_OPTS='overlay2.mount_program=/usr/bin/fuse-overlayfs'
        echo "[engine]" > /etc/containers/containers.conf
        echo "cgroup_manager = \"cgroupfs\"" >> /etc/containers/containers.conf
        echo "events_logger = \"file\"" >> /etc/containers/containers.conf

        echo "Downloading RPMs:"
        for RPM in ${{inputs.package-urls}}; do
          wget -P rpms ${RPM};
        done

        SUITE=""
        if [ -n "${{inputs.suite}}" ]; then SUITE="-s ${{inputs.suite}}"; fi

        CONTAINER=$(uuidgen)
        ./dnf-testing.sh -c $CONTAINER build jjb

        TESTS=($(./dnf-testing.sh -c $CONTAINER $SUITE list))
        mkdir "test-results"
        TEST_DIR=`readlink -f "test-results"`
        parallel -j2 ./dnf-testing.sh --container "$CONTAINER" $SUITE run --junit-directory "$TEST_DIR" --noxfail "{}" ::: "${TESTS[@]}"
