---
name: Nightly DNF CI host container build
on:
  schedule:
    - cron:  '0 2 * * *'  # at 2am UTC
#  push:
#    branches:
#      - ci-container-test

jobs:
  container-build:
    name: Container build
    runs-on: ubuntu-latest
    steps:
      - name: Build the container
        run: |
          DATE=`date "+%F"`
          IMAGE="ghcr.io/rpm-software-management/dnf-ci-host"

          echo ${{secrets.CONTAINER_PAT}} | docker login ghcr.io -u dnf-bot --password-stdin

          docker build -t ${IMAGE}:${DATE} -t ${IMAGE}:latest -<<EOF
          FROM fedora:latest
          RUN dnf -y update
          RUN dnf -y install dnf-plugins-core
          RUN dnf -y copr enable rpmsoftwaremanagement/rpm-gitoverlay
          RUN dnf -y install rpm-gitoverlay fuse-overlayfs parallel podman wget
          RUN dnf clean all  # remove dnf cache to make the image smaller
          EOF

          docker push ${IMAGE}:${DATE}
          docker push ${IMAGE}:latest
