---
name: Build DNF5 containers on quay.io
on:
  schedule:
    - cron: '0 4 * * *' # at 4am UTC, 2 hours after nightlies are built
  workflow_dispatch:


# from https://github.com/marketplace/actions/push-to-registry
jobs:
  build-multiplatform-container-file:
    name: Build images # Build and push multi-platform images
    strategy:
      fail-fast: false
      matrix:
        name:
          - dnf5
          - dnf5-nightly
          #- dnf5-testing
          #- dnf5-testing-nightly
        tag:
          - 38
          - 39
          - 40
          - 41
          - latest
          - rawhide
        platform:
          - linux/amd64
          - linux/arm64
          - linux/ppc64le
          - linux/s390x

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build Image
      id: build_image_multiplatform
      uses: redhat-actions/buildah-build@v2
      with:
        image: fedora-${{ matrix.name }}
        tags: ${{ matrix.tag }}
        platforms: ${{ matrix.platform }}
        containerfiles: |
          containerfiles/Containerfile
        build-args: |
          TAG=${{ matrix.tag }}
          NAME=${{ matrix.name }}

    - name: Echo Outputs
      run: |
        echo "Image: ${{ steps.build_image_multiplatform.outputs.image }}"
        echo "Tags: ${{ steps.build_image_multiplatform.outputs.tags }}"
        echo "Tagged Image: ${{ steps.build_image_multiplatform.outputs.image-with-tag }}"

    - name: Run image
      run: |
        podman run --rm ${{ steps.build_image_multiplatform.outputs.image }}:${{ matrix.tag }}

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image_multiplatform.outputs.image }}
        tags: ${{ steps.build_image_multiplatform.outputs.tags }}
        registry: quay.io/rpmsoftwaremanagement
        username: ${{ secrets.QUAY_IO_REGISTRY_USERNAME }}
        password: ${{ secrets.QUAY_IO_REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
