---
name: Nightly builds in Fedora Copr
on:
  schedule:
    - cron:  '0 0 * * *'  # at midnight UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/rpm-software-management/dnf-ci-host
    strategy:
      fail-fast: false  # don't fail all matrix jobs if one of them fails
      matrix:
        project: [dnf-nightly, dnf5-unstable]
        variant: ['', -sanitizers]
        exclude:
          - project: dnf5-unstable
            variant: -sanitizers
    steps:
      - name: Check out sources
        uses: actions/checkout@v2

      - name: Setup CI
        id: setup-ci
        uses: ./.github/actions/setup-ci
        with:
          copr-user: ${{secrets.COPR_USER}}
          copr-api-token: ${{secrets.COPR_API_TOKEN}}
          # we don't want the workflow to continuously fail on forks
          fail-without-copr: false

      - name: Build in Copr
        if: steps.setup-ci.outputs.copr-user
        run: rpm-gitoverlay build-overlay -s overlays/${{matrix.project}} rpm copr --owner ${{steps.setup-ci.outputs.copr-user}} --project ${{matrix.project}}${{matrix.variant}}
